### ISSUE TITLE
limo_yuen_ttest_boot

### ISSUE THREAD

**Issue by GRousselet** [LIMO-EEG-Toolbox/limo_eeg#1]
limo_cluster_test returns an error when called from limo_yen_ttest boot:

Index exceeds matrix dimensions.

Error in limo_cluster_test (line 52)
        if sum(ori_f(posclusterslabelmat==C)) >= maxclustersum_th;

Error in limo_yuen_ttest_boot (line 132)

**Comment by CPernet** [comment]
that's because we always go trough limo_stat_values 1st which doesn't do that way anymore .. check from line 1011 - best solution I can think of is too make the two subfunctions of  limo_stat_values as new functions and call them as needed from limo_yuen_ttest ?

**Comment by GRousselet** [comment]
ok, the problem was solved after updating the call to limo_yuen_ttest in limo_yuen_ttest_boot
