### ISSUE TITLE
CL and CL_list not defined in limo_ecluster_test.m

### ISSUE THREAD

**Issue by cathymanning** [LIMO-EEG-Toolbox/limo_eeg#12]
'CL' and 'CL_list' are not defined in limo_ecluster_test.m so errors are returned when function tries to output pval.

**Comment by EN-Brain-Imaging-of-Tumours** [comment]
can you give me the context in which you use the function - it is called by [limo_clustering](https://github.com/LIMO-EEG-Toolbox/limo_eeg/blob/master/limo_clustering.m) but i cannot see any output errors from running from the GUI ?? 

thx

**Comment by CPernet** [comment]
can you give me the context in which you use the function - it is called by [limo_clustering](https://github.com/LIMO-EEG-Toolbox/limo_eeg/blob/master/limo_clustering.m) but i cannot see any output errors from running from the GUI ?? 

thx

**Comment by cathymanning** [comment]
Hi

I have been using it as a standalone function in my MATLAB script after using limo_ecluster_make.m. I have been in touch with Guillaume who suggested using these functions in this way and said I should post a bug report - let me know if I can give any more information.

Best wishes

Cathy
________________________________

**Comment by CPernet** [comment]
If you call limo_clustering it should perform the all thing fine - that the way we do it within the toolbox.
If you put some data and the bit of script / line of code how you call this, I'm happy to look into it though.

**Comment by CPernet** [comment]
now pushed to master - fixed
