### ISSUE TITLE
Batch 1st level analyses in LIMO

### ISSUE THREAD

**Issue by neurolinguist** [LIMO-EEG-Toolbox/limo_eeg#19]
Dear Dr. Pernet,

I am trying to apply LIMO to my EEG data. In "Batch 1st level analyses,”  I can import the file listing all the set files, and I can read the categorical_variable.txt. However, the "glm" always fails, with the message as follows. Could I ask any suggestions for the failure? Thank you in advance.
------------
Error using limo_pcout (line 37)
Principal Component Projection cannot be computed, more observations than variables are needed
------------

Sincerely,

Shingo Tokimoto

**Comment by CPernet** [comment]
the error 'Principal Component Projection cannot be computed, more observations than variables are needed' says you cannot use WLS - ie  switch to 'OLS'

**Comment by neurolinguist** [comment]
Dear Dr. Pernet,

Thank you very much for the quick reply. I have understood the solution.

Sincerely,

Shingo Tokimoto
