### ISSUE TITLE
Two within categorical conditions in LIMO

### ISSUE THREAD

**Issue by neurolinguist** [LIMO-EEG-Toolbox/limo_eeg#20]
Dear Dr. Pernet,

Let me ask the format of category specification. My experiment is designed with 2-by-2 conditions with two levels for each. The number of event-markers for epoching are eight with two markers corresponding to each level. I wrote "category-variables.txt" with two columns and with two rows ending the first row with ";." However, the 2*2 design is not recognized is design matrix, and the matrix is represented as 8*8. Could you give me any advice? Thank you in advance.

Sincerely,

Shingo Tokimoto

**Comment by neurolinguist** [comment]
Dear Dr. Pernet,

Thank you for the reply and the instruction page. Yes, I intended to make the category.txt for "N-conditions with/without interactions." I have 24 participants and have made a STUDY structure including them. I consulted "trialinfo" in "STUDY.datasetinfo" in VARIABLE. The beginning of the 'type" field is as follows (The event marker is recorded by BrainVisionRecorder).

'S  4'
'S  2'
'S  4'
'S  2'
'S  4'
'S  2'
'S  4'
'S  3'
'S  4'
'S  3'
'S  2'
'S  4'
'S  1'

The experimental design is 2-by-2, and thus I re-coded the event markers as follows. My intention here is that S1 and S2 correspond to "1" and S3 and S4 to "2" for the 2 levels of the first factor respectively and that S1 and S3 correspond to "3" and S2 and S4 to "4" for the 2 levels of the second factor respectively again.

2 4
1 4
2 4
1 4
2 4
1 4
2 4
2 3
2 4
2 3

However, the design matrix appears as 8*8 not as 2*2. Could you point out what is wrong with me? Thank you in advance again.

Sincerely,

Shingo Tokimoto

**Comment by CPernet** [comment]
your design matrix should have only 4 columns, 2 factor 1 and 2 factor 2 -- why would you expect 22?

**Comment by neurolinguist** [comment]
Dear Dr. Pernet,

Thank you for the reply again. Yes, I am expecting 4 columns, but Design matrix has 8 columns, as attached below.

![2-by-2_design](https://user-images.githubusercontent.com/40905302/44557051-bb4afa00-a777-11e8-8f75-ecf627bea971.png)

Is this correct for the intended analysis? Thank you again.

Shingo Tokimoto

**Comment by CPernet** [comment]
yes, assuming you specified full factorial -- now remember that this is useful for single subject analyses; very unlikely that you can do any group analysis with such design.
