### ISSUE TITLE
Error messages during model parameter estimate

### ISSUE THREAD

**Issue by r91522831** [LIMO-EEG-Toolbox/limo_eeg#25]
I tried to follow the LIMO tutorial materials I got from the 2018 San Diego workshop. When I ran Study >> LIMO Beta >> Estimate Model Parameters (channel) as instructed in the tutorial .pdf. Two error messages popped up after creating an empty folder 'derivatives'. One of the messages is "undefined function or variable 'ft_warning'.", and the second message is "EEGLAB error in function std_limo() at line 176: Undefined function or variable 'chanlocname'." 

I am using EEGLAB 15 and LIMO v2.0 with Matlab R2017b on a Macbook.

Is there a solution to fix the issue? Thank you.

**Comment by CPernet** [comment]
undefined function or variable 'ft_warning'." indicates that Field Trip is not installed -- strange enough the study function from eeglab should have handled that @nucleuscub ; download via the plugin manager and this should work

**Comment by r91522831** [comment]
Downloading via the plugin manager does not work. It makes the option "LInear MOdeling of EEG Data (BETA)" disappear from the "Study" drop-down list. Is this an EEGLAB issue?

**Comment by CPernet** [comment]
yes this is an EEGLAB issue -- have you tried with EEGLAB dev version (https://github.com/sccn/eeglab/tree/develop) pinging @arnodelorme @nucleuscub

**Comment by r91522831** [comment]
I tried EEGLAB dev version. The LIMO downloaded via the plugin manager still does show the "LInear MOdeling of EEG Data (BETA)" option in the "Study" drop-down list.

The option shows up only when I manually put the limo_eeg-master cloned from here into the eeglab-develop/plugins folder. This time the error message becomes "std_limo error: Fieldtrip extension must be installed. (Error occurred in function std_limo() at line 128)."

Should I post a new issue at https://github.com/sccn/eeglab ?

**Comment by CPernet** [comment]
sure post it on the mailing list -- but the issue is that Fieldtrip is not installed ; if both LIMOEEG and Fieldtrip are there, it's no problem ; note that this is only to create the chanlocs automatically, and you can bypass this (I'll make that happen so STUDY can still run)

**Comment by r91522831** [comment]
Thank you for the help. The working combination is using the EEGLAB dev version with the limo_eeg-master cloned from here plus the Fieldtrip installed.
