### ISSUE TITLE
Undefined function cubehelixmap

### ISSUE THREAD

**Issue by VisLab** [LIMO-EEG-Toolbox/limo_eeg#4]
Undefined function 'cubehelixmap' for input arguments of type 'char'.

Error in limo_display_image>color_images_ (line 305)
    cc(1:32,:)=flipud(cubehelixmap('decrease',32));

Error in limo_display_image (line 173)
cc=color_images_(scale,LIMO);

Error in limo_display_results (line 1255)
            limo_display_image(LIMO,toplot,mask,mytitle)

Error in runBCI2000LimoModelSpectralLevel2 (line 25)
limo_display_results(1, fileName, analysisDir, p, MCC, LIMO, flag)
 
>> cubehelixmap
Undefined function or variable 'cubehelixmap'.
 
>> which cubehelixmap
'cubehelixmap' not found.

**Comment by CPernet** [comment]
check your 'external' folder is in the path - that function should be in there

**Comment by VisLab** [comment]
Suggest adding path in eegplugin_limo.m:

```
    if ~exist('pop_loadeep')
%         p = which('eegplugin_limo.m');
%         p = p(1:findstr(p,'eegplugin_limo.m')-1);
%         addpath( p );
        myPath = fileparts(which('eegplugin_limo'));
        addpath(genpath(myPath));
    end;
```

**Comment by CPernet** [comment]
yeh I do it from limo_eeg but I'll ask Ramon to do that 
@nucleuscub can you check how we should handle this

thx
