### ISSUE TITLE
Factors interactions with group in Repeated Measures Anova BUG

### ISSUE THREAD

**Issue by disbeat** [LIMO-EEG-Toolbox/limo_eeg#9]
File: limo_random_roboust.m
Line: 1363

H0_Rep_ANOVA_Interaction_with_gp = squeeze(tmp_boot_H0_Rep_ANOVA_Interaction_with_gp(:,:,i,:)); % save each interaction effect as F/p values

tmp_boot_H0_Rep_ANOVA_Interaction_with_group is of dimension [electrodes, timesamples, factor, 2(F/p), NBOOT] so it is missing a dimension in the squeeze. Should be:

H0_Rep_ANOVA_Interaction_with_gp = squeeze(tmp_boot_H0_Rep_ANOVA_Interaction_with_gp(:,:,i,:,:));

Best regards,
-- Marco Simões
IBILI, University of Coimbra, Portugal

**Comment by CPernet** [comment]
fixed thx
